// Generated by   : ImageConverter Mono Online
// Generated from : batt.png
// Time generated : Thu, 07 May 20 22:59:14 +0200  (Server timezone: CET)
// Image Size     : 12x4 pixels
// Memory usage   : 6 bytes


#if defined(__AVR__)
    #include <avr/pgmspace.h>
    #define imagedatatype const uint8_t
#elif defined(__PIC32MX__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#elif defined(__arm__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#endif

imagedatatype batt[] PROGMEM={
0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xF9, 0xF9, 0xF9, 0xFF, 0xF6, 
};
