// Generated by   : ImageConverter Mono Online
// Generated from : cell.png
// Time generated : Thu, 07 May 20 23:01:36 +0200  (Server timezone: CET)
// Image Size     : 11x4 pixels
// Memory usage   : 5.5 bytes


#if defined(__AVR__)
    #include <avr/pgmspace.h>
    #define imagedatatype const uint8_t
#elif defined(__PIC32MX__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#elif defined(__arm__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#endif

imagedatatype cell[] PROGMEM={
0xF8, 0xF8, 0xF0, 0xFC, 0xFC, 0xF0, 0xFE, 0xFE, 0xF0, 0xFF, 0xFF, 
};
