// Generated by   : ImageConverter Mono Online
// Generated from : lft.png
// Time generated : Thu, 07 May 20 23:08:46 +0200  (Server timezone: CET)
// Image Size     : 3x5 pixels
// Memory usage   : 1.875 bytes


#if defined(__AVR__)
    #include <avr/pgmspace.h>
    #define imagedatatype const uint8_t
#elif defined(__PIC32MX__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#elif defined(__arm__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#endif

imagedatatype lft[] PROGMEM={
0xE4, 0xEA, 0xF1, 
};
