// Generated by   : ImageConverter Mono Online
// Generated from : right.png
// Time generated : Thu, 07 May 20 23:11:47 +0200  (Server timezone: CET)
// Image Size     : 3x5 pixels
// Memory usage   : 1.875 bytes


#if defined(__AVR__)
    #include <avr/pgmspace.h>
    #define imagedatatype const uint8_t
#elif defined(__PIC32MX__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#elif defined(__arm__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#endif

imagedatatype right[] PROGMEM={
0xF1, 0xEA, 0xE4, 
};
