// Generated by   : ImageConverter Mono Online
// Generated from : s_lft.png
// Time generated : Mon, 11 May 20 05:01:50 +0200  (Server timezone: CET)
// Image Size     : 3x5 pixels
// Memory usage   : 1.875 bytes


#if defined(__AVR__)
    #include <avr/pgmspace.h>
    #define imagedatatype const uint8_t
#elif defined(__PIC32MX__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#elif defined(__arm__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#endif

imagedatatype s_lft[] PROGMEM={
0xE4, 0xEE, 0xFF, 
};
