// Generated by   : ImageConverter Mono Online
// Generated from : s_up.png
// Time generated : Mon, 11 May 20 04:54:33 +0200  (Server timezone: CET)
// Image Size     : 5x3 pixels
// Memory usage   : 1.875 bytes


#if defined(__AVR__)
    #include <avr/pgmspace.h>
    #define imagedatatype const uint8_t
#elif defined(__PIC32MX__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#elif defined(__arm__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#endif

imagedatatype s_up[] PROGMEM={
0xFC, 0xFE, 0xFF, 0xFE, 0xFC, 
};
