// Generated by   : ImageConverter Mono Online
// Generated from : scroll_line.png
// Time generated : Thu, 14 May 20 18:43:47 +0200  (Server timezone: CET)
// Image Size     : 5x41 pixels
// Memory usage   : 25.625 bytes


#if defined(__AVR__)
    #include <avr/pgmspace.h>
    #define imagedatatype const uint8_t
#elif defined(__PIC32MX__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#elif defined(__arm__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#endif

imagedatatype scroll_line[] PROGMEM={
0x00, 0x02, 0xF9, 0x02, 0x00, 0x00, 0x00, 0xFF, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x00, 0x00, 0x00,   // 0x0010 (16) pixels
0x00, 0xFF, 0x00, 0x00, 0x00, 0x80, 0x3F, 0x80, 0x00, 0xFE, 0xFE, 0xFF, 0xFE, 0xFE, 
};
