// Generated by   : ImageConverter Mono Online
// Generated from : scroll_bar.png
// Time generated : Thu, 14 May 20 19:02:57 +0200  (Server timezone: CET)
// Image Size     : 5x11 pixels
// Memory usage   : 6.875 bytes


#if defined(__AVR__)
    #include <avr/pgmspace.h>
    #define imagedatatype const uint8_t
#elif defined(__PIC32MX__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#elif defined(__arm__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#endif

imagedatatype scroll_bar[] PROGMEM={
0xFE, 0xFF, 0xFF, 0xFF, 0xFE, 0xFB, 0xFF, 0xFF, 0xFF, 0xFB, 
};
