// Generated by   : ImageConverter Mono Online
// Generated from : scroll_line_down.png
// Time generated : Thu, 14 May 20 18:49:40 +0200  (Server timezone: CET)
// Image Size     : 5x2 pixels
// Memory usage   : 1.25 bytes


#if defined(__AVR__)
    #include <avr/pgmspace.h>
    #define imagedatatype const uint8_t
#elif defined(__PIC32MX__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#elif defined(__arm__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#endif

imagedatatype scroll_line_down[] PROGMEM={
0xFC, 0xFD, 0xFE, 0xFD, 0xFC, 
};
