// Generated by   : ImageConverter Mono Online
// Generated from : up.png
// Time generated : Thu, 07 May 20 23:14:48 +0200  (Server timezone: CET)
// Image Size     : 5x3 pixels
// Memory usage   : 1.875 bytes


#if defined(__AVR__)
    #include <avr/pgmspace.h>
    #define imagedatatype const uint8_t
#elif defined(__PIC32MX__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#elif defined(__arm__)
    #define PROGMEM
    #define imagedatatype const unsigned char
#endif

imagedatatype up[] PROGMEM={
0xFC, 0xFA, 0xF9, 0xFA, 0xFC, 
};
